// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuu8ZuT4ZsPJaKbKs274NWB_QIcFMAYzs',
    appId: '1:801859189006:web:0fffc62e65986335c17f5f',
    messagingSenderId: '801859189006',
    projectId: 'notify-f2eb3',
    authDomain: 'notify-f2eb3.firebaseapp.com',
    storageBucket: 'notify-f2eb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdhCTxcBALXEo3is9FTLxCrYVwmsy06Aw',
    appId: '1:801859189006:android:f6369a12cb1381edc17f5f',
    messagingSenderId: '801859189006',
    projectId: 'notify-f2eb3',
    storageBucket: 'notify-f2eb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAulkwogFYmAf1DvbDMKABv2uP_-8VHDgw',
    appId: '1:801859189006:ios:c81c90c258debb68c17f5f',
    messagingSenderId: '801859189006',
    projectId: 'notify-f2eb3',
    storageBucket: 'notify-f2eb3.appspot.com',
    iosClientId: '801859189006-4lc5vks2drt62j8mu4f848g76ulqi08a.apps.googleusercontent.com',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAulkwogFYmAf1DvbDMKABv2uP_-8VHDgw',
    appId: '1:801859189006:ios:866dc292448510f8c17f5f',
    messagingSenderId: '801859189006',
    projectId: 'notify-f2eb3',
    storageBucket: 'notify-f2eb3.appspot.com',
    iosClientId: '801859189006-ll840sp6eoia8fjqadd47hdcvqq7v3hh.apps.googleusercontent.com',
    iosBundleId: 'com.example.notify.RunnerTests',
  );
}
